apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:   
  selector:
    matchLabels:
      app: gitlab
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - image: gitlab/gitlab-ce:latest
        name: gitlab
        ports:
        - containerPort: 80
          name: gitlab-http
        - containerPort: 443
          name: gitlab-https
        - containerPort: 22
          name: gitlab-ssh 
        volumeMounts:
        - mountPath: /etc/gitlab 
          name: gitlab-config 
        - mountPath: /var/log/gitlab 
          name: gitlab-log 
        - mountPath: /var/opt/gitlab 
          name: gitlab-data
      volumes:
      - name: gitlab-data
        hostPath:
          path: /usr/iqeq/gitlib/data
      - name: gitlab-config
        hostPath:
          path: /usr/iqeq/gitlib/config
      - name: gitlab-log
        hostPath:
          path: /usr/iqeq/gitlib/logs
---
kind: Service
apiVersion: v1
metadata:
  name: gitlab-service
  labels:
    app: gitlab-service
  namespace: gitlab
spec:
  selector:
    app: gitlab
  ports:
  - protocol: TCP
    name: gitlab-https
    port: 443
    targetPort: 443
  - protocol: TCP
    name: gitlab-http
    port: 80
    targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: gitlab-ssh-service
  labels:
    app: gitlab-ssh-service
  namespace: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
  - protocol: TCP
    name: gitlab-ssh
    port: 22
    targetPort: 22
    nodePort: 30000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab-ingress
  namespace: gitlab
  annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false" # 强制http重定向到https
      nginx.ingress.kubernetes.io/proxy-body-size: "0" # 设置client_max_body_size为0
spec:
  rules:
  - host: gitlib.xx.com  # 你主机要绑定的域名，后面会通过nginx转发
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab-service
          servicePort: 80 